default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("RAILS_DB_HOST") %>
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test